-- V1: esquema inicial (equivale a lo que Hibernate generaba con ddl-auto=update).
-- Compatible con PostgreSQL y H2 (modo PostgreSQL, usado en tests).

create table students (
    id                bigint generated by default as identity primary key,
    first_name        varchar(255) not null,
    last_name         varchar(255) not null,
    email             varchar(255) not null,
    phone             varchar(255) not null,
    registration_date date         not null,
    expiration_date   date         not null,
    status            varchar(255) not null,
    constraint uk_students_email unique (email)
);

create table users (
    id         bigint generated by default as identity primary key,
    username   varchar(255) not null,
    password   varchar(255) not null,
    role       varchar(255) not null,
    enabled    boolean      not null,
    student_id bigint       not null,
    constraint uk_users_username unique (username),
    constraint uk_users_student unique (student_id),
    constraint fk_users_student foreign key (student_id) references students (id)
);

create table prices (
    id            bigint generated by default as identity primary key,
    type          varchar(255)   not null,
    amount        numeric(19, 2) not null,
    duration_days integer        not null,
    active        boolean        not null,
    created_at    timestamp(6)   not null
);

create table payments (
    id           bigint generated by default as identity primary key,
    payment_date date           not null,
    period_start date           not null,
    period_end   date           not null,
    amount_paid  numeric(19, 2) not null,
    student_id   bigint         not null,
    price_id     bigint         not null,
    constraint fk_payments_student foreign key (student_id) references students (id),
    constraint fk_payments_price foreign key (price_id) references prices (id)
);

create table invoices (
    id             bigint generated by default as identity primary key,
    invoice_number integer        not null,
    issue_date     date           not null,
    period_start   date           not null,
    period_end     date           not null,
    total          numeric(19, 2) not null,
    student_id     bigint         not null,
    constraint uk_invoices_number unique (invoice_number),
    constraint fk_invoices_student foreign key (student_id) references students (id)
);
