-- V2: codigo de registro de un solo uso, log de notificaciones, indices y cuentas admin sin estudiante.

-- Registro por invitacion (ver docs/DECISIONS.md D-004)
alter table students add column registration_code_hash varchar(64);
alter table students add column registration_code_expires_at timestamp(6);

-- Las cuentas ADMIN no pertenecen a un estudiante
alter table users alter column student_id drop not null;

-- El estado EXPIRED se elimino: la membresia vencida se deriva de expiration_date (D-005)
update students set status = 'INACTIVE' where status = 'EXPIRED';

-- Idempotencia de recordatorios (D-008)
create table notification_logs (
    id             bigint generated by default as identity primary key,
    student_id     bigint       not null,
    type           varchar(50)  not null,
    reference_date date         not null,
    sent_at        timestamp(6) not null,
    constraint uk_notification_student_type_ref unique (student_id, type, reference_date),
    constraint fk_notification_student foreign key (student_id) references students (id)
);

-- Indices para las consultas frecuentes (vencimientos, filtros, historial de pagos)
create index idx_students_expiration_date on students (expiration_date);
create index idx_students_status_expiration on students (status, expiration_date);
create index idx_payments_student_id on payments (student_id);
create index idx_payments_payment_date on payments (payment_date);
create index idx_prices_type_active on prices (type, active);
